config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: "", path_names: { sign_in: "login", sign_out: "logout", sign_up: "register" }
  resources :portfolios, except: [:show]
  get "angular-items", to: "portfolios#angular"
  get "portfolio/:id", to: "portfolios#show", as: "portfolio_show"

  get "about", to: "pages#about"
  get "contact", to: "pages#contact"
  resources :blogs do
    member do
      get :toggle_status
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: "pages#home"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  enum status: { draft: 0, published: 1 }
  extend FriendlyId
  friendly_id :title, use: :slugged

  validates :title, :body, presence: true

  belongs_to :topic
end

app/models/concerns/placeholder.rb
module Placeholder
  extend ActiveSupport::Concern

  def self.image_generator(height:, width:)
    "http://placehold.it/#{height}"
  end
end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
  has_many :technologies
  accepts_nested_attributes_for :technologies,
                                reject_if: lambda { |attrs| attrs["name"].blank? }

  includes Placeholder
  validates_presence_of :title, :body, :main_image, :thumb_image

  def self.angular
    where(subtitle: "Angular")
  end

  scope :ruby_on_rails_portfolio_items, -> { where(subtitle: "Ruby on Rails") }

  after_initialize :set_defaults

  def set_defaults
    self.main_image ||= Placeholder.image_generator(height: 600, width: 600)
    self.thumb_image ||= Placeholder.image_generator(height: 300, width: 300)
  end
end

app/models/skill.rb
class Skill < ApplicationRecord
  includes Placeholder
  validates_presence_of :title, :percent_utilized

  after_initialize :set_defaults

  def set_defaults
    self.badge ||= Placeholder.image_generator(height: "200", width: "200")
  end
end

app/models/technology.rb
class Technology < ApplicationRecord
  belongs_to :portfolio
end

app/models/topic.rb
class Topic < ApplicationRecord
  validates_presence_of :title

  has_many :blogs
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates_presence_of :name

  def first_name
    self.name.split.first
  end

  def last_name
    self.name.split.last
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include DeviseWhitelist
  include SetSource

  def current_user
    super || OpenStruct.new(name: "Guest User", first_name: "Guest", last_name: "User", email: "guest@example.com")
  end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy, :toggle_status]
  layout "blog"

  # GET /blogs
  # GET /blogs.json
  def index
    @blogs = Blog.all
  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: "Blog was successfully created." }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1
  # PATCH/PUT /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: "Blog was successfully updated." }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: "Blog was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def toggle_status
    if @blog.draft?
      @blog.published!
    else
      @blog.draft!
    end
    redirect_to blogs_url, notice: "Post status has been updated."
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_blog
    @blog = Blog.friendly.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def blog_params
    params.require(:blog).permit(:title, :body)
  end
end

app/controllers/concerns/devise_whitelist.rb
module DeviseWhitelist
  extend ActiveSupport::Concern

  included do
    before_action :configure_permitted_parameters, if: :devise_controller?
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
end

app/controllers/concerns/set_source.rb
module SetSource
  extend ActiveSupport::Concern

  included do
    before_action :set_source
  end

  def set_source
    session[:source] = params[:q] if params[:q]
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @blog = Blog.all
    @skills = Skill.all
  end

  def about
  end

  def contact
  end
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
  layout "portfolio"

  def index
    @portfolio_items = Portfolio.all
  end

  def angular
    @angular_portfolio_items = Portfolio.angular
  end

  def new
    @portfolio_items = Portfolio.new
    3.times { @portfolio_items.technologies.build }
  end

  def create
    @portfolio_item = Portfolio.new(params.require(:portfolio).permit(:title, :subtitle, :body, technologies_attributes: [:name]))

    respond_to do |format|
      if @portfolio_item.save
        format.html { redirect_to portfolios_path, notice: "Your portfolio item is now live." }
      else
        format.html { render :new }
      end
    end
  end

  def edit
    @portfolio_item = Portfolio.find(params[:id])
  end

  def update
    @portfolio_item = Portfolio.find(params[:id])
    respond_to do |format|
      if @portfolio_item.update(params.require(:portfolio).permit(:title, :subtitle, :body))
        format.html { redirect_to portfolios_path, notice: "Your portfolio item is now updated." }
      else
        format.html { render :edit }
      end
    end
  end

  def show
    @portfolio_item = Portfolio.find(params[:id])
  end

  def destroy
    @portfolio_item = Portfolio.find(params[:id])
    @portfolio_item.destroy
    respond_to do |format|
      format.html { redirect_to portfolios_path, notice: "Post was removed." }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def sample_helper
    "<p>My helper</p>".html_safe
  end
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
end

app/views/blogs/_form.html.erb
<%= form_with(model: blog, local: true) do |form| %>
  <% if blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
      <% blog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<h1>Editing Blog</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Show', @blog %> |
<%= link_to 'Back', blogs_path %>

app/views/blogs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Blogs</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @blogs.each do |blog| %>
      <tr>
        <td><%= blog.title.upcase %></td>
        <td><%= blog.body %></td>
        <td><%= link_to blog.status, toggle_status_blog_path(blog) %></td>
        <td><%= link_to 'Show', blog %></td>
        <td><%= link_to 'Edit', edit_blog_path(blog) %></td>
        <td><%= link_to 'Destroy', blog, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Blog', new_blog_path %>

app/views/blogs/new.html.erb
<h1>New Blog</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Back', blogs_path %>

app/views/blogs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @blog.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @blog.body %>
</p>

<%= link_to 'Edit', edit_blog_path(@blog) %> |
<%= link_to 'Back', blogs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DevcampPortfolio | My Portfolio</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= render "shared/nav" %>
    <%= yield %>

    <% if session[:source]%>
      <p>Thanks for visiting me from <%= session[:source]%> </p>
    <%end%>
  </body>
</html>

app/views/layouts/blog.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DevcampPortfolio | My Portfolio</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'blogs', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <% if session[:source]%>
      <p>Thanks for visiting me from <%= session[:source]%> </p>
    <%end%>
    <%= render "shared/nav" %>
    <%= yield %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    
  </body>
</html>

app/views/layouts/portfolio.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DevcampPortfolio | My Portfolio</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'portfolios', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= render "shared/nav" %>
    <%= yield %>

    <% if session[:source]%>
      <p>Thanks for visiting me from <%= session[:source]%> </p>
    <%end%>
  </body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/home.html.erb
<h1><%= "Hi, " + current_user.first_name if current_user%></h1>
<p>Find me in app/views/pages/home.html.erb</p>
<h1> Blogs </h1>
<%= @blog.inspect%>
<h1> Skills </h1>
<%= @skills.inspect%>

<hr>
<%= sample_helper%>

app/views/portfolios/angular.html.erb
<h1>Angular Portfolio Items </h1>
<%= link_to "Create New Item" ,new_portfolio_url%>

<% @angular_portfolio_items.each do |portfolio_item|%>
  <p><%= link_to portfolio_item.title, portfolio_show_path(portfolio_item) %></p>
  <p><%= portfolio_item.subtitle%> </p>
  <p><%= portfolio_item.body%> </p>
  <%= image_tag portfolio_item.thumb_image unless portfolio_item.thumb_image.nil? %>
  <p><%= link_to "Edit" , edit_portfolio_path(portfolio_item)%><p>
  <p><%= link_to "Delete" , portfolio_path(portfolio_item), method: :delete, data: {confirm: 'Are you sure?'}%><p>
<% end%>

app/views/portfolios/edit.html.erb
<h1>Create a portfolio Item </h1>

<%= form_for(@portfolio_item) do |form| %>
  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
  
  <div class="field">
    <%= form.label :subtitle %>
    <%= form.text_field :subtitle %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/portfolios/index.html.erb
<h1> Portfolio Items </h1>
<%= link_to "Create New Item" ,new_portfolio_url%>

<% @portfolio_items.each do |portfolio_item|%>
  <p><%= link_to portfolio_item.title, portfolio_show_path(portfolio_item) %></p>
  <p><%= portfolio_item.subtitle%> </p>
  <p><%= portfolio_item.body%> </p>
  <%= image_tag portfolio_item.thumb_image unless portfolio_item.thumb_image.nil? %>
  <p><%= link_to "Edit" , edit_portfolio_path(portfolio_item)%><p>
  <p><%= link_to "Delete" , portfolio_path(portfolio_item), method: :delete, data: {confirm: 'Are you sure?'}%><p>
<% end%>

app/views/portfolios/new.html.erb
<h1>Create a portfolio Item </h1>

<%= form_with model: @portfolio_items, url: portfolios_path do |form| %>
  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
  
  <div class="field">
    <%= form.label :subtitle %>
    <%= form.text_field :subtitle %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <ul>
    <%= form.fields_for :technologies do |technology_form| %>
      <li>
        <%= technology_form.label :name%>
        <%= technology_form.text_field :name%>
      </li>
    <% end %>
  </ul>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/portfolios/show.html.erb
<h1> <%= @portfolio_item.title%></h1>
<em> <%= @portfolio_item.subtitle%></em>
<p> <%= @portfolio_item.body%></p>
<%= image_tag @portfolio_item.main_image%>
<h2>Technologies Used</h2>
<% @portfolio_item.technologies.each do |t| %>
  <p><%= t.name %></p>
<% end %>

app/views/shared/_nav.html.erb
<% if current_user.is_a?(User)%>
  <%=link_to "Logout", destroy_user_session_path, method: :delete%>
<% else %>
  <%=link_to "Register", new_user_registration_path%>
  <%=link_to "Login", new_user_session_path%>
<% end %>